language: ruby

rvm:
#- "1.9.3"
#  - "2.0"
#  - "2.1"
  - "2.2"
#  - ruby-head

gemfile:
  - gemfiles/rails_4_2.gemfile
 # - gemfiles/rails_4_1.gemfile
  # - gemfiles/rails_4_0.gemfile
  # - gemfiles/rails_3_2.gemfile

before_install: gem install bundler

before_script:
  - cp config/database.travis.yml config/database.yml
  - cp config/database.travis.yml test/dummy/config/database.yml
  - sh -c "if [ '$DB' = 'pgsql' ]; then psql -c 'DROP DATABASE IF EXISTS rails_db;' -U postgres; fi"
  - sh -c "if [ '$DB' = 'pgsql' ]; then psql -c 'create database rails_db;' -U postgres; fi"
  - mysql -e "drop database if exists rails_db;" -uroot
  - mysql -e "create database IF NOT EXISTS rails_db;" -uroot

cache: bundler

bundler_args: --without development --jobs=3 --retry=3 --path=../vendor/bundle

env:
  - DB=sqlite
  - DB=mysql
  - DB=postgresql

script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake test

matrix:
  fast_finish: true

notifications:
  email: false