language: ruby

rvm:
  - "1.9.3"
#  - "2.0"
#  - "2.1"
  - "2.2"
#  - ruby-head

gemfile:
  - gemfiles/rails_4_2.gemfile
 # - gemfiles/rails_4_1.gemfile
  # - gemfiles/rails_4_0.gemfile
  # - gemfiles/rails_3_2.gemfile

before_install: gem install bundler

before_script:
  - cp config/database.travis.yml config/database.yml
  - cp config/database.travis.yml test/dummy/config/database.yml

  - psql -c 'DROP DATABASE IF EXISTS rails_db;' -u postgres
  - psql -c 'create database rails_db;' -U postgres

  - mysql -e 'drop database if exists rails_db;'
  - mysql -e 'create database rails_db;'

cache: bundler

bundler_args: --without development --jobs=3 --retry=3 --path=../vendor/bundle

env:
  - DB=sqlite
  - DB=mysql
  - DB=postgresql

script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake test

matrix:
  fast_finish: true

notifications:
  email: false